<a href="https://colab.research.google.com/github/a2gs/GoogleColab/blob/master/quickstart_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01862314, -0.387774  , -0.24389096, -0.13665824, -0.36212054,
        -0.33634004,  0.31267795,  0.2162807 , -0.339611  , -0.11777066]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.11353704, 0.07562084, 0.08732309, 0.09720749, 0.07758588,
        0.07961208, 0.15235052, 0.13835   , 0.0793521 , 0.09906095]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.5305893

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2981 - accuracy: 0.9128
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1420 - accuracy: 0.9587
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1066 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0878 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0739 - accuracy: 0.9775


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0788 - accuracy: 0.9754


[0.07884906977415085, 0.9753999710083008]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.60784145e-06, 1.74900265e-06, 8.53980418e-06, 4.04140766e-04,
        1.13403419e-11, 3.95108970e-07, 1.23283874e-11, 9.99573886e-01,
        1.43134059e-07, 9.52148093e-06],
       [5.84445388e-07, 9.93943759e-05, 9.99877334e-01, 2.20198717e-06,
        7.37826429e-15, 8.81495339e-07, 5.95435949e-06, 3.10693723e-12,
        1.35684113e-05, 2.20501277e-14],
       [5.45460743e-08, 9.99248922e-01, 1.02968123e-04, 2.04144180e-06,
        6.04936868e-05, 1.12994730e-05, 2.61172772e-05, 2.00292707e-04,
        3.47427267e-04, 3.13876598e-07],
       [9.99989152e-01, 2.70141109e-09, 6.78283277e-06, 7.94316506e-08,
        1.13707843e-08, 1.49181062e-06, 1.54179247e-06, 7.58679391e-07,
        8.80267637e-10, 1.16155014e-07],
       [1.05191641e-04, 2.49716714e-09, 9.39954134e-06, 1.06209797e-07,
        9.57346201e-01, 7.79466336e-06, 1.15636067e-05, 6.33608943e-05,
        6.18177137e-06, 4.24502268e-02]], dtype=float32)>